
 /**
  * This template file was generated by dynaTrace client.
  * The dynaTrace community portal can be found here: http://community.dynatrace.com/
  * For information how to publish a plugin please visit http://community.dynatrace.com/plugins/contribute/
  **/ 

package com.mycompany.myplugin;

import com.dynatrace.diagnostics.pdk.*;
import java.util.Collection;
import java.util.logging.Logger;


public class AM extends AvailMonitor implements Monitor {

	private static final Logger log = Logger.getLogger(AM.class.getName());
	private static final String METRIC_GROUP = "Availability Monitor";
	private static final String MSR_TCP = "TCP Check";
	private static final String MSR_TRIP = "TCP Lock Time";
	private static final String MSR_DNS = "DNS Resolved";
	private static final String MSR_REV_DNS = "Reverse DNS Resolved";
	private static final String MSR_PING = "Ping Check";

	@Override
	public Status setup(MonitorEnvironment env) throws Exception {
		return new Status(Status.StatusCode.Success);
	}

	@Override
	public Status execute(MonitorEnvironment env) throws Exception {
		Status result = super.execute(env);

		Collection<MonitorMeasure> measures;
		if ((measures = env.getMonitorMeasures(METRIC_GROUP, MSR_TCP)) != null) {
			for (MonitorMeasure measure : measures)
				measure.setValue(returnTCPConnect());
		}
		if ((measures = env.getMonitorMeasures(METRIC_GROUP, MSR_TRIP)) != null) {
			for (MonitorMeasure measure : measures)
				measure.setValue(returnTrip());
		}
		if ((measures = env.getMonitorMeasures(METRIC_GROUP, MSR_DNS)) != null) {
			for (MonitorMeasure measure : measures)
				measure.setValue(returnDNSConnect());
		}
		if ((measures = env.getMonitorMeasures(METRIC_GROUP, MSR_REV_DNS)) != null) {
			for (MonitorMeasure measure : measures)
				measure.setValue(returnReverseDNSConnect());
		}
		if ((measures = env.getMonitorMeasures(METRIC_GROUP, MSR_PING)) != null) {
			for (MonitorMeasure measure : measures)
				measure.setValue(returnPing());
		}

		return result;
	}
	
	@Override
	public void teardown(MonitorEnvironment env) throws Exception {
		super.teardown(env);
	}
}
